### PR TITLE
Initial web frontend - provides a map, a UI and geocoding 

### PR DESCRIPTION
**Pull request by JamesCraster**
This pull request provides a web client that provides a mapbox map, restricted to the UK and with geocoding restricted to London, with map controls. The user can enter start and end locations within London and have them appear on the map. The user can also click to add start/end locations and drag/swap the start and end locations. GeoJSON is used to draw a straight line between them; in future this line will be a route provided by the server.
## Type of change

- [ ] Bug fix
- [x] New feature
- [ ] Documentation
- [ ] New algorithm

## Additional dependencies

* mapbox-gl-js
* A modified version of mapbox-gl-directions is provided in the mapbox-gl-directions folder; if futher changes need to be made to this, run npm build within /mapbox-gl-directions and the new mapbox-gl-directions.js file will be produced in the /dist folder

## Tests

The UI has been tested manually over localhost.
## Issues fixes

List any issues this closes: (none)

## Checklist
Please ensure you have done the following:

- [ ] Code conforms to the projects style guidelines -> I have used vscode's default formatter for html/js/css, although this is not a project guideline

- [ ] New code documented using [google docstyle](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html)

- [ ] Updated documentation of any changed code

- [ ] Any additional dependencies have been added to the appropriate location (e.g. `setup.py` or `requirements.txt`)

- [ ] Unit tests written and passing. Tests should prove that fix is effective or new feature works as expected

- [ ] Code needs to run on the cluster? Tag database administrator in the pull request review to configure.

### CODE REVIEW

**Comment by PatrickOHara** [comment]
Quick (and maybe dumb) question @JamesCraster : why is there so many lines in the pull request?

You must have a very fast typing speed! 🥇

**Comment by JamesCraster** [comment]
I use a javascript formatter that is different from the mapbox-directions-plugin formatter, so whenever I edit their code and reformat this will change all the lines in that source file, also I included the /dist directory in their code, which will change whenever I build their plugin. This setup isn't very nice, but I need to modify their plugin - they call the mapbox API for all things, their camera animations are a bit wonky, and I think rerouting on each drag event would be too much for us. I'm not sure if maintaining a small fork would be more clear in terms of those git diffs.

**Comment by PatrickOHara** [comment]
I see - are there other advantages/disadvantages to forking their repo?

For example if they update their source code to fix a bug, can we pull their changes?

Also worth thinking about how forking would affect integration with the frontend @ChristyNou  is building.

**Comment by JamesCraster** [comment]
Being able to pull their changes would be useful, although I don't think we would want to merge too often - our use of the plugin isn't in line with their aims so we would spend a little time merging each time we did it.

I think the main benefit of the fork would be being able to keep track of the changes we make to the plugin without those changes being lost among the changes to the rest of the urbanroute repo.

Then there is the issue of where to put it so we can access the /dist directory, the options I can see are:
* Cloning the fork into the /apps repo and replacing the existing plugin with it each time we make changes. 
* Maybe this problem could be a good use of [git submodules](https://git-scm.com/book/en/v2/Git-Tools-Submodules)?
* The other option might be to make a fork and publish to npm private, but then we would then need to use webpack/browserify - I'm not sure if that's a good idea.

I'm not sure how this would effect integration with @ChristyNou 's work; I think that is an important issue. I would be inclined to create a fork, although perhaps it would be best to evaluate mapbox and the plugin for our needs before doing so.

**Comment by JamesCraster** [comment]
Which repo is your code in Christina?

**Pull request merged**
